sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  ssh_known_hosts:
  - 46.101.190.192
branches:
  only:
  - test
env:
  global:
  - REMOTE_USER=builder
  - REMOTE_HOST=46.101.190.192
  - PORT=8080
  
before_install:
- openssl aes-256-cbc -K $encrypted_2b560cfeafab_key -iv $encrypted_2b560cfeafab_iv -in travis_rsa.enc -out travis_rsa -d
- chmod +x mvnw
- rm travis_rsa.enc
- chmod 600 travis_rsa
- mv travis_rsa  ~/.ssh/id_rsa
- docker build -t "abjdocker/hackernewscloneserver:101".
- set +x
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
after_success:
- if [ "$TRAVIS_BRANCH" == "test" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push abjdocker/hackernewscloneserver:$"TRAVIS_BUILD_NUMBER"; docker logout;
  fi
