version: '3'
services:
  mongo:
    image: mongo:3.4
    ports:
    - "27017:27017"
    volumes:
    - /data/hackernews
    restart: always
  # api:
  #   build: .
  #   ports:
  #   - "8090:8080"
  #   volumes:
  #   - .:/code
  #   links:
  #   - mongo
  
